name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  buildWindows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.3.7

      - name: Setup Haxelib
        shell: cmd
        run: |
          haxelib setup C:/haxelib
          haxelib install hxcpp --quiet
          haxe -version

      - name: Run Setup
        shell: cmd
        run: |
          haxe -cp ./setup -D analyzer-optimize -main Main --interp

      - name: Build HXCPP
        shell: cmd
        run: |
          cd tools/hxcpp
          haxe compile.hxml

      - name: Get Short SHA
        uses: benjlevesque/short-sha@v3.0
        id: short-sha

      - name: Compile
        shell: cmd
        run: |
          haxelib run lime build windows -D GIT_COMMIT=${{ steps.short-sha.outputs.sha }} --app-version="4.0.0-${{ github.run_id }}"

      - name: Publish Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windowsBuild
          path: export/release/windows/bin
